services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: 0:0
    ports:
      - 8188:8080
    volumes:
      - /qvo870:/data/qvo870
      - /jd480:/data/jd480
      - ./filebrowser:/config
    restart: unless-stopped
    networks:
        - proxy-network
networks:
  proxy-network:
    external:
      name: internal-network