services:
  headscale:
    container_name: headscale
    volumes:
        - ${CONFIG_DIR}:/etc/headscale
        - ${KEYS_DIR}:/var/lib/headscale
    ports:
        - 8580:8080
        - 8590:9090
    user: 0:0
    image: headscale/headscale
    command: serve
    restart: unless-stopped
    env_file:
      - stack.env
      
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    container_name: headscale-ui
    restart: unless-stopped
    ports:
        - 8500:8080